name: Publish Docker Image

on:
  schedule:
    - cron: "0 0 * * 0"
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        hardware: [{ arch: "geminilake" }]
        software: [{ dsm: "7.2", gpl: "64570", linux: "4.4.x" }]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log into DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Log into GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: "${{ github.repository }}:${{ matrix.hardware.arch }}-${{ matrix.software.dsm }},ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:${{ matrix.hardware.arch }}-${{ matrix.software.dsm }}"
          platforms: linux/amd64,linux/arm64
          cache-from: type=registry,ref=ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:cache
          cache-to: type=registry,ref=ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:cache,mode=max
          build-args: |
            ARCH=${{ matrix.hardware.arch }}
            DSM_VERSION=${{ matrix.software.dsm }}
            GPL_VERSION=${{ matrix.software.gpl }}
            LINUX_VERSION=${{ matrix.software.linux }}
